function status = func_save_json(NameJson, time1, lat1,lon1,alt1, lat2,lon2,alt2, lat3,lon3,alt3, d12,d13,d23, freq, band)

ID = fopen(NameJson, 'wt');

fprintf(ID, [...
'{\n'...
'   "time": "%s",\n'...
'   "transponders":[\n'...
], time1);

fmt = [...
'      {\n'...
'         "transponderID":%d,\n'...
'         "transponder location":{\n'...
'            "lat":%.10f,\n'...
'            "lon":%.10f,\n'...
'            "alt":%.1f\n'...
'         },\n'...
'         "transponder frequency":%G,\n'...
'         "transponder bandwidth":%G\n'...
'      }'...
];

fprintf(ID, [fmt ',\n'], 1, lat1, lon1, alt1, freq, band);
fprintf(ID, [fmt ',\n'], 2, lat2, lon2, alt2, freq, band);
fprintf(ID, [fmt '\n'], 3, lat3, lon3, alt3, freq, band);

fprintf(ID, [...
'   ],\n'...
'   "diffs":{\n'...
'      "12":%.10G,\n'...
'      "13":%.10G,\n'...
'      "23":%.10G\n'...
'   }\n'...
'}\n'...
], d12*1e-9, d13*1e-9, d23*1e-9);

status = fclose(ID);

end

